services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  shortener_service:
    image: shortener-service:latest
    build:
      context: ./shortener-service
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-localhost:3000}
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
  
  webapp:
    image: webapp:latest
    build:
      context: ./webapp
    environment:
      - API_SERVER=${API_SERVER:-http://localhost:8080}
    ports:
      - "3000:80"
    depends_on:
      - shortener_service



volumes:
  mongo_data: