
spring:
    application:
        name: shortener
    data:
      mongodb:
        uri: mongodb://localhost:27017/shortener
        database: shortener
        auto-index-creation: true
      redis:
        host: localhost
        port: 6379