spring:
    application:
        name: shortener
    data:
      mongodb:
        uri: mongodb://localhost:27017/shortener
        database: shortener
        auto-index-creation: true
      redis:
        host: localhost
        port: 6379
    web:
      cors:
        allowed-origins:
          - "http://localhost:3000"
        allowed-methods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
api:
  key:
    header: X-API-KEY
    value: shortener-api-key