spring:
  application:
    name: shortener-api
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:27017/${MONGODB_DATABASE}?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  web:
    cors:
      allowed-origins: "http://localhost:4321"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    db:
      enabled: true