spring:
  application:
    name: shortener-service
  cache:
    type: redis
  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      url: ${REDIS_URL}
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    db:
      enabled: true